<?php

namespace App\Entity;

use App\Repository\NmdUserConfigurationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NmdUserConfigurationRepository::class)
 */
class NmdUserConfiguration
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isMailSendDuringUserCreation;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isUserReferenceAutoGenerateDuringUserCreation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userId;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isNewUserValidByDefault;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isAuthorizedRdvByBo;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $partRetainedForRdvByBo;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isBlocagePointage;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsMailSendDuringUserCreation(): ?bool
    {
        return $this->isMailSendDuringUserCreation;
    }

    public function setIsMailSendDuringUserCreation(?bool $isMailSendDuringUserCreation): self
    {
        $this->isMailSendDuringUserCreation = $isMailSendDuringUserCreation;

        return $this;
    }

    public function getIsUserReferenceAutoGenerateDuringUserCreation(): ?bool
    {
        return $this->isUserReferenceAutoGenerateDuringUserCreation;
    }

    public function setIsUserReferenceAutoGenerateDuringUserCreation(?bool $isUserReferenceAutoGenerateDuringUserCreation): self
    {
        $this->isUserReferenceAutoGenerateDuringUserCreation = $isUserReferenceAutoGenerateDuringUserCreation;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->userId;
    }

    public function setUserId(?int $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getIsNewUserValidByDefault(): ?bool
    {
        return $this->isNewUserValidByDefault;
    }

    public function setIsNewUserValidByDefault(?bool $isNewUserValidByDefault): self
    {
        $this->isNewUserValidByDefault = $isNewUserValidByDefault;

        return $this;
    }

    public function getIsAuthorizedRdvByBo(): ?bool
    {
        return $this->isAuthorizedRdvByBo;
    }

    public function setIsAuthorizedRdvByBo(?bool $isAuthorizedRdvByBo): self
    {
        $this->isAuthorizedRdvByBo = $isAuthorizedRdvByBo;

        return $this;
    }

    public function getPartRetainedForRdvByBo(): ?float
    {
        return $this->partRetainedForRdvByBo;
    }

    public function setPartRetainedForRdvByBo(?float $partRetainedForRdvByBo): self
    {
        $this->partRetainedForRdvByBo = $partRetainedForRdvByBo;

        return $this;
    }

    public function getIsBlocagePointage(): ?bool
    {
        return $this->isBlocagePointage;
    }

    public function setIsBlocagePointage(?bool $isBlocagePointage): self
    {
        $this->isBlocagePointage = $isBlocagePointage;

        return $this;
    }
}
